# **POLAR Task 2: Polarization Classification**

In [2]:
!head -n 10 ./processed/task2_polarization_type_no_id.txt

text|political|racial/ethnic|religious|gender/sexual|other
ကိုယ့်နိုင်ငံကြီး အေးချမ်းသွားရင် ကိုယ့်နိုင်ငံ ပြန်တာပေါ့ သူတို့နိုင်ငံမှာ အရမ်း အနှိမ်ခံ ရတယ်ဗျာ|0|1|0|0|0
တကယ် လေ နိုင်ငံခြား သား တွေ အကုန် လုံး ကို တစ် ယောက် မ ကျန် အကုန် ပြန်လွှတ် စေ ချင် တာ ဂျပန် မှ လွဲ အကုန်လုံး ကို အဲ့လို သာ လုပ် လိုက် သူတို့ နိုင်ငံ သေချာပေါက် စီးပွားရေး ကျ ဆင်း ကုန်မှာ အေးရော။|0|1|0|0|0
ဂျပန် ထဲ မြန်မာ တွေ ဝင် လာ ပြီ ဆိုတော့ သူတို့ လန့် သွား တယ် ထင်တယ်|0|1|0|0|0
ဒီ အကြောင်း တွေ ကို  ဂျပန် လို ပြော ပြီး  တင် သင့် တယ် အခု လည်း ခွဲခြား ခြင်း ခံ ရ ပါတယ် သူတို့ က နေရာ က လိုချင် အပါး က ခို|0|1|0|0|0
တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာလို့ အများ ကြီး ဂျပန် ကို ဝင်လာ ကြ တာ လဲ|0|1|0|0|0
တူတူ ပဲ မ ရေ အလုပ် ထဲ က သူနာပြု မ လူ ကို မ တူ သ လို မ တန် သ လို အချိုး အမျိုးမျိုး နဲ့ စကား ပြောတယ် ညီမ ဆေး တိုက် ချိန် သူ့ ကို ပြ ရင် လုံးဝ မ ကြည့် ဘူး ဘာမှ လည်း ပြန် မ ပြော ဘူး|0|1|0|0|0
ထိုင်း မှာ နေ ရ တာ အရမ်း ပင်ပန်း လာ ပြီ ဗျာ|0|0|0|0|1
ဘယ် ဥ က ပေါက် တဲ့ ကောင် လဲ မ သိ ဘူး|0|0|0|0|0
မင်း မ ကောင်း တော့ ပြည်သူ ပြည်သား တွေ ပါ ဒုက္ခ ရောက် ရ တဲ့ ဘဝ|1|0|0|0|0

In [3]:
import pandas as pd
import csv

file_path = "/home/thant_syn/exp/polar/processed/task2_polarization_type_no_id.txt"

columns = [
    "text",
    "political",
    "racial/ethnic",
    "religious",
    "gender/sexual",
    "other"
]

rows = []

with open(file_path, "r", encoding="utf-8-sig", newline="") as f:
    for line_no, line in enumerate(f, start=1):
        line = line.rstrip("\r\n")

        if not line:
            continue

        # Skip the header
        if line_no == 1 and line.startswith("text|political|"):
            continue

        # Split from the right to preserve pipes in the text
        parts = line.rsplit("|", 5)

        if len(parts) != 6:
            print(f"Skipping malformed line {line_no}")
            continue

        rows.append(parts)

df2 = pd.DataFrame(rows, columns=columns)

# Convert labels to numeric values
label_cols = columns[1:]
df2[label_cols] = df2[label_cols].apply(
    pd.to_numeric, errors="coerce"
)

print("Dataset shape:", df2.shape)
display(df2.head())
print("\nMissing values:")
print(df2.isna().sum())

Skipping malformed line 134
Skipping malformed line 135
Skipping malformed line 174
Skipping malformed line 175
Skipping malformed line 176
Skipping malformed line 177
Skipping malformed line 474
Skipping malformed line 475
Skipping malformed line 486
Skipping malformed line 487
Skipping malformed line 2126
Skipping malformed line 2127
Skipping malformed line 2128
Skipping malformed line 2129
Skipping malformed line 2130
Skipping malformed line 2131
Skipping malformed line 2132
Skipping malformed line 2133
Skipping malformed line 2134
Skipping malformed line 2135
Skipping malformed line 2136
Skipping malformed line 2137
Skipping malformed line 2138
Skipping malformed line 2139
Skipping malformed line 2140
Skipping malformed line 2141
Skipping malformed line 2142
Skipping malformed line 2146
Skipping malformed line 2147
Skipping malformed line 2148
Skipping malformed line 2358
Skipping malformed line 2359
Skipping malformed line 2728
Skipping malformed line 2729
Skipping malformed line 5515
Skipping malformed line 5516
Skipping malformed line 5523
Skipping malformed line 5524
Skipping malformed line 5558
Skipping malformed line 5559
Skipping malformed line 5662
Skipping malformed line 5663
Skipping malformed line 5721
Skipping malformed line 5722
Skipping malformed line 5723
Skipping malformed line 5724
Skipping malformed line 5727
Skipping malformed line 5728
Skipping malformed line 5729
Skipping malformed line 5730
Skipping malformed line 5731
Skipping malformed line 5761
Skipping malformed line 5762
Skipping malformed line 6023
Skipping malformed line 6024
Dataset shape: (10295, 6)

,text,political,racial/ethnic,religious,gender/sexual,other
0,ကိုယ့်နိုင်ငံကြီး အေးချမ်းသွားရင် ကိုယ့်နိုင်င...,0,1.0,0,0.0,0
1,တကယ် လေ နိုင်ငံခြား သား တွေ အကုန် လုံး ကို တစ်...,0,1.0,0,0.0,0
2,ဂျပန် ထဲ မြန်မာ တွေ ဝင် လာ ပြီ ဆိုတော့ သူတို့ ...,0,1.0,0,0.0,0
3,ဒီ အကြောင်း တွေ ကို ဂျပန် လို ပြော ပြီး တင် ...,0,1.0,0,0.0,0
4,တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာလိ...,0,1.0,0,0.0,0

Missing values:
text               0
political          0
racial/ethnic    601
religious          0
gender/sexual    601
other              0
dtype: int64

In [4]:
df2.tail()

,text,political,racial/ethnic,religious,gender/sexual,other
10290,ဝင်ကြည့်လိုက်တယ် အရူးတွေဖြေနေတာတွေ့တော့ ဆက်ကို...,0,0.0,0,0.0,0
10291,စောက်ရှက်မဲ့တာတော့လွန်တယ်ကွယ် ပင်စင်လွန်ဂျပုကက...,1,1.0,0,0.0,0
10292,စောက်ကျက်သရေ ကို ယုတ် တယ်,0,0.0,0,0.0,0
10293,ဒီအဖွားကြီးကန်ချပစ်,1,1.0,0,0.0,0
10294,ဘက်စုံ ဒုက္ခပေး နေ တာ ဘဲ . .,1,1.0,0,0.0,0

## Data Cleaning 

### Missing Values

In [5]:
label_cols = [
    "political",
    "racial/ethnic",
    "religious",
    "gender/sexual",
    "other"
]

print("Missing values:")
print(df2[label_cols].isna().sum())

print("\nRows with missing labels:")
display(df2[df2[label_cols].isna().any(axis=1)])

Missing values:
political          0
racial/ethnic    601
religious          0
gender/sexual    601
other              0
dtype: int64

Rows with missing labels:

,text,political,racial/ethnic,religious,gender/sexual,other
595,မြန်မာ့ သမိုင်း မှာ စောက် ရှက် မ ရှိ ဆုံး အယုတ...,1,NaN,0,NaN,0
596,မြန်မာ့ တပ်မတော်က ရခိုင် ပြည်နယ် တွင်း မှာ ထကြ...,1,NaN,0,NaN,0
597,ဒီ ခွေး တွေ ကို ဖမ်းမိ ရင်ဆေး ကုပေး ရ တာ နဲ့ က...,1,NaN,0,NaN,0
598,ရွာပြင် ထုတ်ခံ ကြ ရ မြန်မာ တွေ ဟာ သာသနာပြုပြင်...,0,NaN,1,NaN,0
599,နယ်ချဲ့ လက်ဝေခံ ဘာရိန်းစော်ဘွား သည် အုံကြွ မှု...,1,NaN,0,NaN,0
...,...,...,...,...,...,...
1191,ခွေးဝဲစားယီးပဲယျောင့် မ အေဘေးခွေးသား လူမ မှား ...,0,NaN,0,NaN,0
1192,USDP = ဖွတ်ခွေးသခိုး,0,NaN,0,NaN,0
1193,က လိမ်် က ကျစ်ကောင် တွေ,0,NaN,0,NaN,0
1194,တရခံ အစစ် ကို ရဲ တွေ သိတယ်ယုတ်မာ နေ ကြ တာ အမူ ...,0,NaN,0,NaN,1
1195,အမျိုးမျိုး ဒုက္ခ ပေး ကန့်လန့် တိုက် နေ တာ ခွေ...,0,NaN,0,NaN,0

### Check Invalid labels

In [6]:
for col in label_cols:
    invalid = df2.loc[
        ~df2[col].isin([0, 1]) & df2[col].notna(),
        col
    ]
    print(f"{col}: {invalid.unique()}")

political: []
racial/ethnic: []
religious: []
gender/sexual: []
other: []

### Replace NaN values with 0

In [7]:
label_cols = [
    "political",
    "racial/ethnic",
    "religious",
    "gender/sexual",
    "other"
]

df = df2.copy()

df[label_cols] = df[label_cols].fillna(0).astype(int)

print(df.shape)
print(df[label_cols].isna().sum())
print(df[label_cols].dtypes)

display(df.head())

(10295, 6)
political        0
racial/ethnic    0
religious        0
gender/sexual    0
other            0
dtype: int64
political        int64
racial/ethnic    int64
religious        int64
gender/sexual    int64
other            int64
dtype: object

,text,political,racial/ethnic,religious,gender/sexual,other
0,ကိုယ့်နိုင်ငံကြီး အေးချမ်းသွားရင် ကိုယ့်နိုင်င...,0,1,0,0,0
1,တကယ် လေ နိုင်ငံခြား သား တွေ အကုန် လုံး ကို တစ်...,0,1,0,0,0
2,ဂျပန် ထဲ မြန်မာ တွေ ဝင် လာ ပြီ ဆိုတော့ သူတို့ ...,0,1,0,0,0
3,ဒီ အကြောင်း တွေ ကို ဂျပန် လို ပြော ပြီး တင် ...,0,1,0,0,0
4,တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာလိ...,0,1,0,0,0

In [8]:
df.tail()

,text,political,racial/ethnic,religious,gender/sexual,other
10290,ဝင်ကြည့်လိုက်တယ် အရူးတွေဖြေနေတာတွေ့တော့ ဆက်ကို...,0,0,0,0,0
10291,စောက်ရှက်မဲ့တာတော့လွန်တယ်ကွယ် ပင်စင်လွန်ဂျပုကက...,1,1,0,0,0
10292,စောက်ကျက်သရေ ကို ယုတ် တယ်,0,0,0,0,0
10293,ဒီအဖွားကြီးကန်ချပစ်,1,1,0,0,0
10294,ဘက်စုံ ဒုက္ခပေး နေ တာ ဘဲ . .,1,1,0,0,0

---

### Check Label Distribution

In [23]:
label_cols = [
    "political",
    "racial/ethnic",
    "religious",
    "gender/sexual",
    "other"
]

print("Dataset shape:", df.shape)

print("\nPositive examples per category:")
print(df[label_cols].sum().sort_values(ascending=False))

print("\nLabel distribution:")
for col in label_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

Dataset shape: (10295, 6)

Positive examples per category:
political        3108
other            2276
racial/ethnic     909
religious         906
gender/sexual     758
dtype: int64

Label distribution:

political
political
0    7187
1    3108
Name: count, dtype: int64

racial/ethnic
racial/ethnic
0    9386
1     909
Name: count, dtype: int64

religious
religious
0    9389
1     906
Name: count, dtype: int64

gender/sexual
gender/sexual
0    9537
1     758
Name: count, dtype: int64

other
other
0    8019
1    2276
Name: count, dtype: int64

## Prepare input text & label

In [9]:
X = df["text"].astype(str).to_numpy()
y = df[label_cols].to_numpy(dtype="float32")

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (10295,)
y shape: (10295, 5)

In [10]:
X

array(['ကိုယ့်နိုင်ငံကြီး အေးချမ်းသွားရင် ကိုယ့်နိုင်ငံ ပြန်တာပေါ့ သူတို့နိုင်ငံမှာ အရမ်း အနှိမ်ခံ ရတယ်ဗျာ',
       'တကယ် လေ နိုင်ငံခြား သား တွေ အကုန် လုံး ကို တစ် ယောက် မ ကျန် အကုန် ပြန်လွှတ် စေ ချင် တာ ဂျပန် မှ လွဲ အကုန်လုံး ကို အဲ့လို သာ လုပ် လိုက် သူတို့ နိုင်ငံ သေချာပေါက် စီးပွားရေး ကျ ဆင်း ကုန်မှာ အေးရော။',
       'ဂျပန် ထဲ မြန်မာ တွေ ဝင် လာ ပြီ ဆိုတော့ သူတို့ လန့် သွား တယ် ထင်တယ်',
       ..., 'စောက်ကျက်သရေ ကို ယုတ် တယ်', 'ဒီအဖွားကြီးကန်ချပစ်',
       'ဘက်စုံ ဒုက္ခပေး နေ တာ ဘဲ . .'], shape=(10295,), dtype=object)

In [11]:
y

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]], shape=(10295, 5), dtype=float32)

### Split the dataset

We'll use an 80% training, 10% validation, and 10% test split.

In [27]:
%pip install iterative-stratification

Collecting iterative-stratification
  Downloading iterative_stratification-0.1.9-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: numpy in /home/thant_syn/ml_env/lib/python3.12/site-packages (from iterative-stratification) (2.5.2)
Requirement already satisfied: scipy in /home/thant_syn/ml_env/lib/python3.12/site-packages (from iterative-stratification) (1.18.0)
Requirement already satisfied: scikit-learn in /home/thant_syn/ml_env/lib/python3.12/site-packages (from iterative-stratification) (1.9.0)
Requirement already satisfied: joblib>=1.4.0 in /home/thant_syn/ml_env/lib/python3.12/site-packages (from scikit-learn->iterative-stratification) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /home/thant_syn/ml_env/lib/python3.12/site-packages (from scikit-learn->iterative-stratification) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/thant_syn/ml_env/lib/python3.12/site-packages (from scikit-learn->iterative-stratification) (3.6.0)
Downloading iterative_stratification-0.1.9-py3-none-any.whl (8.5 kB)
Installing collected packages: iterative-stratification
Successfully installed iterative-stratification-0.1.9
Note: you may need to restart the kernel to use updated packages.

In [12]:
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit

split1 = MultilabelStratifiedShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, temp_idx = next(split1.split(X, y))

X_train, X_temp = X[train_idx], X[temp_idx]
y_train, y_temp = y[train_idx], y[temp_idx]

split2 = MultilabelStratifiedShuffleSplit(
    n_splits=1,
    test_size=0.50,
    random_state=42
)

val_idx, test_idx = next(split2.split(X_temp, y_temp))

X_val, X_test = X_temp[val_idx], X_temp[test_idx]
y_val, y_test = y_temp[val_idx], y_temp[test_idx]

print("Training:", X_train.shape, y_train.shape)
print("Validation:", X_val.shape, y_val.shape)
print("Testing:", X_test.shape, y_test.shape)

Training: (8236,) (8236, 5)
Validation: (1029,) (1029, 5)
Testing: (1030,) (1030, 5)

### Tokenize and pad Burmese text

In [13]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Hyperparameters
MAX_WORDS = 20000
MAX_LEN = 100
EMBEDDING_DIM = 128

# Fit tokenizer on training data only
tokenizer = Tokenizer(
    num_words=MAX_WORDS,
    oov_token="<OOV>"
)
tokenizer.fit_on_texts(X_train)

# Convert text to sequences
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_val_seq = tokenizer.texts_to_sequences(X_val)
X_test_seq = tokenizer.texts_to_sequences(X_test)

# Pad sequences
X_train_pad = pad_sequences(
    X_train_seq, maxlen=MAX_LEN, padding="post", truncating="post"
)
X_val_pad = pad_sequences(
    X_val_seq, maxlen=MAX_LEN, padding="post", truncating="post"
)
X_test_pad = pad_sequences(
    X_test_seq, maxlen=MAX_LEN, padding="post", truncating="post"
)

vocab_size = min(MAX_WORDS, len(tokenizer.word_index) + 1)

print("Vocabulary size:", vocab_size)
print("Training shape:", X_train_pad.shape)
print("Validation shape:", X_val_pad.shape)
print("Test shape:", X_test_pad.shape)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1791606399.205515     582 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1791606399.206752     582 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1791606399.979293     582 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1791606402.556605     582 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1791606402.557220     582 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

Vocabulary size: 20000
Training shape: (8236, 100)
Validation shape: (1029, 100)
Test shape: (1030, 100)

## **Build the BiLSTM model**

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Embedding, Bidirectional, LSTM, Dense, Dropout
)
from tensorflow.keras.callbacks import EarlyStopping

model = Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=EMBEDDING_DIM,
        mask_zero=True
    ),
    Bidirectional(LSTM(64, return_sequences=True)),
    Dropout(0.3),
    Bidirectional(LSTM(32)),
    Dropout(0.3),
    Dense(32, activation="relu"),
    Dropout(0.2),
    Dense(5, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="binary_accuracy")
    ]
)

model.summary()

E0000 00:00:1791564333.439635   21384 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

history = model.fit(
    X_train_pad,
    y_train,
    validation_data=(X_val_pad, y_val),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping],
    verbose=1
)

Epoch 1/15

E0000 00:00:1791564349.187589   21384 util.cc:131] oneDNN supports DT_BOOL only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.

258/258 ━━━━━━━━━━━━━━━━━━━━ 39s 118ms/step - binary_accuracy: 0.8345 - loss: 0.4474 - val_binary_accuracy: 0.8455 - val_loss: 0.3968
Epoch 2/15
258/258 ━━━━━━━━━━━━━━━━━━━━ 56s 217ms/step - binary_accuracy: 0.8541 - loss: 0.3926 - val_binary_accuracy: 0.8577 - val_loss: 0.3690
Epoch 3/15
258/258 ━━━━━━━━━━━━━━━━━━━━ 57s 220ms/step - binary_accuracy: 0.8775 - loss: 0.3335 - val_binary_accuracy: 0.8606 - val_loss: 0.3557
Epoch 4/15
258/258 ━━━━━━━━━━━━━━━━━━━━ 59s 227ms/step - binary_accuracy: 0.8973 - loss: 0.2822 - val_binary_accuracy: 0.8628 - val_loss: 0.3560
Epoch 5/15
258/258 ━━━━━━━━━━━━━━━━━━━━ 57s 219ms/step - binary_accuracy: 0.9210 - loss: 0.2229 - val_binary_accuracy: 0.8665 - val_loss: 0.3596
Epoch 6/15
258/258 ━━━━━━━━━━━━━━━━━━━━ 57s 223ms/step - binary_accuracy: 0.9373 - loss: 0.1744 - val_binary_accuracy: 0.8603 - val_loss: 0.3977

In [32]:
## evaluate model

from sklearn.metrics import classification_report, f1_score, hamming_loss

y_prob = model.predict(X_test_pad)
y_pred = (y_prob >= 0.5).astype(int)

print("Macro F1:", f1_score(y_test, y_pred, average="macro", zero_division=0))
print("Micro F1:", f1_score(y_test, y_pred, average="micro", zero_division=0))
print("Hamming Loss:", hamming_loss(y_test, y_pred))

print("\nPer-category report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=label_cols,
    zero_division=0
))

33/33 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step
Macro F1: 0.11721082854799014
Micro F1: 0.3025540275049116
Hamming Loss: 0.1378640776699029

Per-category report:
               precision    recall  f1-score   support

    political       0.70      0.49      0.58       311
racial/ethnic       0.00      0.00      0.00        91
    religious       0.00      0.00      0.00        91
gender/sexual       0.00      0.00      0.00        76
        other       0.50      0.00      0.01       228

    micro avg       0.70      0.19      0.30       797
    macro avg       0.24      0.10      0.12       797
 weighted avg       0.42      0.19      0.23       797
  samples avg       0.15      0.14      0.14       797

**ဒေတာ imbalance ဖြစ်မှု ကြောင့် positive text တွေကို detect လုပ်တဲ့အခါမှာ အခက်အခဲတွေဖြစ်နေတာလို့ ထင်မိပါတယ်။**

**တကယ်တမ်းလည်း polar text label တစ်ခုချင်းစီမှာနည်းနေပါတယ်။ ရာ ဂဏန်း‌လောက်ပဲ ရှိတာဆိုတော့ နည်းသွားတာ။ NN model ဆိုတော့ data ကလိုတယ်ဆိုတော့**

---

In [33]:
# Check whether the model predicts any positive labels

import numpy as np
import pandas as pd

label_cols = [
    "political",
    "racial/ethnic",
    "religious",
    "gender/sexual",
    "other"
]

diagnostics = pd.DataFrame({
    "Train positives": y_train.sum(axis=0),
    "Validation positives": y_val.sum(axis=0),
    "Test positives": y_test.sum(axis=0),
    "Predicted positives": (y_prob >= 0.5).sum(axis=0),
    "Mean probability": y_prob.mean(axis=0)
}, index=label_cols)

display(diagnostics.round(3))

,Train positives,Validation positives,Test positives,Predicted positives,Mean probability
political,2486.0,311.0,311.0,219,0.300
racial/ethnic,727.0,91.0,91.0,0,0.111
religious,725.0,90.0,91.0,0,0.092
gender/sexual,606.0,76.0,76.0,0,0.078
other,1821.0,227.0,228.0,2,0.212

---

## Machine Learning Models

### TF-IDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    analyzer="word",
    ngram_range=(1, 2),
    min_df=2,
    max_features=50000,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_val_tfidf = tfidf.transform(X_val)
X_test_tfidf = tfidf.transform(X_test)

print("Train:", X_train_tfidf.shape)
print("Validation:", X_val_tfidf.shape)
print("Test:", X_test_tfidf.shape)

Train: (8236, 10959)
Validation: (1029, 10959)
Test: (1030, 10959)

## Multi-label Linear SVM

In [15]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC

svm = OneVsRestClassifier(
    LinearSVC(
        C=1.0,
        class_weight="balanced",
        max_iter=5000
    )
)

svm.fit(X_train_tfidf, y_train)

OneVsRestClassifier(estimator=LinearSVC(class_weight='balanced', max_iter=5000))

In [16]:
# predict
y_pred_svm = svm.predict(X_test_tfidf)

y_pred_svm

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       ...,
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]], shape=(1030, 5))

In [17]:
from sklearn.metrics import (
    classification_report,
    f1_score
)

print("Macro F1:",
      f1_score(
          y_test,
          y_pred_svm,
          average="macro",
          zero_division=0
      ))

print("Micro F1:",
      f1_score(
          y_test,
          y_pred_svm,
          average="micro",
          zero_division=0
      ))

print("\nPer-category results:")
print(
    classification_report(
        y_test,
        y_pred_svm,
        target_names=label_cols,
        zero_division=0
    )
)

Macro F1: 0.4127104704399359
Micro F1: 0.45894263217097864

Per-category results:
               precision    recall  f1-score   support

    political       0.57      0.62      0.60       311
racial/ethnic       0.23      0.31      0.26        91
    religious       0.46      0.58      0.52        91
gender/sexual       0.26      0.32      0.28        76
        other       0.35      0.48      0.40       228

    micro avg       0.42      0.51      0.46       797
    macro avg       0.37      0.46      0.41       797
 weighted avg       0.43      0.51      0.46       797
  samples avg       0.33      0.36      0.33       797

Since your Task 2 has relatively few examples for gender/sexual, religious, and racial/ethnic, I'd also try character n-gram TF-IDF. 

This can be particularly useful for Burmese because it doesn't depend as heavily on perfect word segmentation.

In [18]:
tfidf_char = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3, 5),
    min_df=2,
    max_features=50000,
    sublinear_tf=True
)

X_train_char = tfidf_char.fit_transform(X_train)
X_test_char = tfidf_char.transform(X_test)

svm_char = OneVsRestClassifier(
    LinearSVC(
        C=1.0,
        class_weight="balanced",
        max_iter=5000
    )
)

svm_char.fit(X_train_char, y_train)

y_pred_char = svm_char.predict(X_test_char)

print(
    "Character TF-IDF + SVM Macro F1:",
    f1_score(
        y_test,
        y_pred_char,
        average="macro",
        zero_division=0
    )
)

Character TF-IDF + SVM Macro F1: 0.6045453498628928

In [20]:
print(
    classification_report(
        y_test,
        y_pred_char,
        target_names=label_cols,
        zero_division=0
    )
)

               precision    recall  f1-score   support

    political       0.72      0.72      0.72       311
racial/ethnic       0.56      0.46      0.51        91
    religious       0.85      0.69      0.76        91
gender/sexual       0.53      0.50      0.51        76
        other       0.51      0.53      0.52       228

    micro avg       0.63      0.61      0.62       797
    macro avg       0.63      0.58      0.60       797
 weighted avg       0.64      0.61      0.62       797
  samples avg       0.42      0.42      0.41       797

## Tune Linear SVC

In [21]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score

for ngram_range in [(2,4), (3,5), (3,6), (4,6)]:

    vectorizer = TfidfVectorizer(
        analyzer="char",
        ngram_range=ngram_range,
        min_df=2,
        max_features=50000,
        sublinear_tf=True
    )

    X_train_char = vectorizer.fit_transform(X_train)
    X_val_char = vectorizer.transform(X_val)

    svm = OneVsRestClassifier(
        LinearSVC(
            C=1.0,
            class_weight="balanced",
            max_iter=5000
        )
    )

    svm.fit(X_train_char, y_train)

    pred = svm.predict(X_val_char)

    macro_f1 = f1_score(
        y_val,
        pred,
        average="macro",
        zero_division=0
    )

    print(
        f"Character {ngram_range}: "
        f"Validation Macro F1 = {macro_f1:.4f}"
    )

Character (2, 4): Validation Macro F1 = 0.6252
Character (3, 5): Validation Macro F1 = 0.5992
Character (3, 6): Validation Macro F1 = 0.5942
Character (4, 6): Validation Macro F1 = 0.5774

In [22]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score

ngram_range = (2, 4)

vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=ngram_range,
    min_df=2,
    max_features=50000,
    sublinear_tf=True
)

X_train_char = vectorizer.fit_transform(X_train)
X_val_char = vectorizer.transform(X_val)

svm = OneVsRestClassifier(
    LinearSVC(
        C=1.0,
        class_weight="balanced",
        max_iter=5000
    )
)

svm.fit(X_train_char, y_train)

pred = svm.predict(X_val_char)

print(
    "Validation Macro F1:",
    round(f1_score(y_val, pred, average="macro", zero_division=0), 4)
)

Validation Macro F1: 0.6252

In [26]:
print(
    classification_report(
        y_val,
        pred,
        target_names=label_cols,
        zero_division=0
    )
)

               precision    recall  f1-score   support

    political       0.70      0.77      0.73       311
racial/ethnic       0.58      0.56      0.57        91
    religious       0.83      0.69      0.75        90
gender/sexual       0.59      0.51      0.55        76
        other       0.52      0.53      0.53       227

    micro avg       0.64      0.64      0.64       795
    macro avg       0.64      0.61      0.63       795
 weighted avg       0.64      0.64      0.64       795
  samples avg       0.43      0.44      0.43       795

---

## Explore the WORD LEVEL SEGMENTATION (OppaWord)

In [27]:
# Save only the text column
df["text"].to_csv(
    "task2_text_raw.txt",
    index=False,
    header=False
)

In [28]:
df.head()

,text,political,racial/ethnic,religious,gender/sexual,other
0,ကိုယ့်နိုင်ငံကြီး အေးချမ်းသွားရင် ကိုယ့်နိုင်င...,0,1,0,0,0
1,တကယ် လေ နိုင်ငံခြား သား တွေ အကုန် လုံး ကို တစ်...,0,1,0,0,0
2,ဂျပန် ထဲ မြန်မာ တွေ ဝင် လာ ပြီ ဆိုတော့ သူတို့ ...,0,1,0,0,0
3,ဒီ အကြောင်း တွေ ကို ဂျပန် လို ပြော ပြီး တင် ...,0,1,0,0,0
4,တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာလိ...,0,1,0,0,0

In [50]:
# Save all five label columns, preserving their order
label_cols = [
    "political",
    "racial/ethnic",
    "religious",
    "gender/sexual",
    "other"
]

df[label_cols].to_csv(
    "task2_labels.csv",
    index=False,
    header=False
)

In [51]:
!head task2_labels.csv

0,1,0,0,0
0,1,0,0,0
0,1,0,0,0
0,1,0,0,0
0,1,0,0,0
0,1,0,0,0
0,0,0,0,1
0,0,0,0,0
1,0,0,0,0
1,0,0,0,0

In [29]:
%pwd

'/home/thant_syn/exp/polar'

In [30]:
!head -n 10 task2_text_raw.txt

ကိုယ့်နိုင်ငံကြီး အေးချမ်းသွားရင် ကိုယ့်နိုင်ငံ ပြန်တာပေါ့ သူတို့နိုင်ငံမှာ အရမ်း အနှိမ်ခံ ရတယ်ဗျာ
တကယ် လေ နိုင်ငံခြား သား တွေ အကုန် လုံး ကို တစ် ယောက် မ ကျန် အကုန် ပြန်လွှတ် စေ ချင် တာ ဂျပန် မှ လွဲ အကုန်လုံး ကို အဲ့လို သာ လုပ် လိုက် သူတို့ နိုင်ငံ သေချာပေါက် စီးပွားရေး ကျ ဆင်း ကုန်မှာ အေးရော။
ဂျပန် ထဲ မြန်မာ တွေ ဝင် လာ ပြီ ဆိုတော့ သူတို့ လန့် သွား တယ် ထင်တယ်
ဒီ အကြောင်း တွေ ကို  ဂျပန် လို ပြော ပြီး  တင် သင့် တယ် အခု လည်း ခွဲခြား ခြင်း ခံ ရ ပါတယ် သူတို့ က နေရာ က လိုချင် အပါး က ခို
တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာလို့ အများ ကြီး ဂျပန် ကို ဝင်လာ ကြ တာ လဲ
တူတူ ပဲ မ ရေ အလုပ် ထဲ က သူနာပြု မ လူ ကို မ တူ သ လို မ တန် သ လို အချိုး အမျိုးမျိုး နဲ့ စကား ပြောတယ် ညီမ ဆေး တိုက် ချိန် သူ့ ကို ပြ ရင် လုံးဝ မ ကြည့် ဘူး ဘာမှ လည်း ပြန် မ ပြော ဘူး
ထိုင်း မှာ နေ ရ တာ အရမ်း ပင်ပန်း လာ ပြီ ဗျာ
ဘယ် ဥ က ပေါက် တဲ့ ကောင် လဲ မ သိ ဘူး
မင်း မ ကောင်း တော့ ပြည်သူ ပြည်သား တွေ ပါ ဒုက္ခ ရောက် ရ တဲ့ ဘဝ
ပူတင် လဲ ဘာ ထူး လဲ တိုက် ခိုက် ခံ ရ ပြီး ဘတ်ကျပ် ပျက် နေ ပြီ

In [31]:
!tail -n 10 task2_text_raw.txt

စကား​ ပြော တာ ကို က​$ အဆင့် မ ရှိ ​ ပြော​ နေ တာ
မဲမရလို့ ရူးကြတော့မှာလား
အရူးစကား
မြန်မာ နိုင်ငံ သည် နှာဗူးမ တွေ ရှိ နေ သ၍ စစ်မှန် တဲ့ အဆိုရှင် များ ဖြစ် မည် မ ဟုတ် ကြောင်း ။
ငါ သိငါ တတ် တွေ အဲ့ကြောင့် ဘယ် တိုင်းရင်းသား တွေ နဲ့ မှ မ တည့် ဘူး
ဝင်ကြည့်လိုက်တယ် အရူးတွေဖြေနေတာတွေ့တော့ ဆက်ကိုမကြည့်တော့တာ
စောက်ရှက်မဲ့တာတော့လွန်တယ်ကွယ် ပင်စင်လွန်ဂျပုကကောဘာတတ်နိုင်မှာလဲ ခွေးဘီလူးနေရာပေးလို့လူရာဝင်သလိုဖြစ်နေတာကို
စောက်ကျက်သရေ ကို ယုတ် တယ်
ဒီအဖွားကြီးကန်ချပစ်
ဘက်စုံ ဒုက္ခပေး နေ တာ ဘဲ . .

### Clean Text

In [33]:
%pip install emoji

Collecting emoji
  Downloading emoji-2.16.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.16.0-py3-none-any.whl (610 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 610.9/610.9 kB 4.3 MB/s  0:00:0036m-:--:--
Installing collected packages: emoji
Successfully installed emoji-2.16.0
Note: you may need to restart the kernel to use updated packages.

In [34]:
import re

import emoji

def clean_text(text):
    # Remove emojis
    text = emoji.replace_emoji(text, replace="")

    # Normalize multiple spaces, tabs, and other whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


input_file = "task2_text_raw.txt"
output_file = "task2_text_clean.txt"

with open(input_file, "r", encoding="utf-8") as fin:
    lines = fin.readlines()

with open(output_file, "w", encoding="utf-8") as fout:
    for line in lines:
        cleaned = clean_text(line)
        fout.write(cleaned + "\n")

print(f"Cleaning complete: {output_file}")

Cleaning complete: task2_text_clean.txt

In [41]:
!head task2_text_clean.txt

ကိုယ့်နိုင်ငံကြီး အေးချမ်းသွားရင် ကိုယ့်နိုင်ငံ ပြန်တာပေါ့ သူတို့နိုင်ငံမှာ အရမ်း အနှိမ်ခံ ရတယ်ဗျာ
တကယ် လေ နိုင်ငံခြား သား တွေ အကုန် လုံး ကို တစ် ယောက် မ ကျန် အကုန် ပြန်လွှတ် စေ ချင် တာ ဂျပန် မှ လွဲ အကုန်လုံး ကို အဲ့လို သာ လုပ် လိုက် သူတို့ နိုင်ငံ သေချာပေါက် စီးပွားရေး ကျ ဆင်း ကုန်မှာ အေးရော။
ဂျပန် ထဲ မြန်မာ တွေ ဝင် လာ ပြီ ဆိုတော့ သူတို့ လန့် သွား တယ် ထင်တယ်
ဒီ အကြောင်း တွေ ကို ဂျပန် လို ပြော ပြီး တင် သင့် တယ် အခု လည်း ခွဲခြား ခြင်း ခံ ရ ပါတယ် သူတို့ က နေရာ က လိုချင် အပါး က ခို
တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာလို့ အများ ကြီး ဂျပန် ကို ဝင်လာ ကြ တာ လဲ
တူတူ ပဲ မ ရေ အလုပ် ထဲ က သူနာပြု မ လူ ကို မ တူ သ လို မ တန် သ လို အချိုး အမျိုးမျိုး နဲ့ စကား ပြောတယ် ညီမ ဆေး တိုက် ချိန် သူ့ ကို ပြ ရင် လုံးဝ မ ကြည့် ဘူး ဘာမှ လည်း ပြန် မ ပြော ဘူး
ထိုင်း မှာ နေ ရ တာ အရမ်း ပင်ပန်း လာ ပြီ ဗျာ
ဘယ် ဥ က ပေါက် တဲ့ ကောင် လဲ မ သိ ဘူး
မင်း မ ကောင်း တော့ ပြည်သူ ပြည်သား တွေ ပါ ဒုက္ခ ရောက် ရ တဲ့ ဘဝ
ပူတင် လဲ ဘာ ထူး လဲ တိုက် ခိုက် ခံ ရ ပြီး ဘတ်ကျပ် ပျက် နေ ပြီ

In [42]:
!time python /home/thant_syn/exp/nmt/oppaWord/oppa_word.py \
  --input /home/thant_syn/exp/polar/task2_text_clean.txt \
  --dict /home/thant_syn/exp/nmt/oppaWord/data/myg2p_mypos.dict \
  --use-bimm-fallback \
  --bimm-boost 150 \
  --space-remove-mode "my_not_num" \
  > task2_text_word.txt

real	0m3.416s
user	0m3.394s
sys	0m0.037s

In [43]:
!head task2_text_word.txt

ကိုယ့် နိုင်ငံ ကြီး အေးချမ်း သွား ရင် ကိုယ့် နိုင်ငံ ပြန် တာ ပေါ့ သူ တို့ နိုင်ငံ မှာ အရမ်း အ နှိမ် ခံ ရ တယ် ဗျာ
တကယ် လေ နိုင်ငံခြားသား တွေ အကုန်လုံး ကို တစ် ယောက်မ ကျန် အကုန် ပြန်လွှတ် စေ ချင် တာ ဂျပန် မှ လွဲ အကုန်လုံး ကို အဲ့လို သာ လုပ် လိုက် သူ တို့ နိုင်ငံ သေချာပေါက် စီးပွားရေး ကျဆင်း ကုန် မှာ အေး ရော ။
ဂျပန် ထဲ မြန်မာ တွေ ဝင်လာ ပြီ ဆို တော့ သူ တို့ လန့် သွား တယ် ထင်တယ်
ဒီ အကြောင်း တွေ ကို ဂျပန် လို ပြော ပြီး တင် သင့် တယ် အခု လည်း ခွဲခြား ခြင်း ခံ ရ ပါတယ် သူ တို့ က နေရာ က လို ချင် အပါး က ခို
တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာ လို့ အများကြီး ဂျပန် ကို ဝင်လာ ကြ တာ လဲ
တူတူ ပဲ မ ရေ အလုပ် ထဲက သူနာပြု မ လူ ကို မ တူ သလို မ တန် သလို အချိုး အမျိုးမျိုး နဲ့ စကားပြော တယ် ညီမ ဆေးတိုက် ချိန် သူ့ ကို ပြ ရင် လုံးဝ မ ကြည့် ဘူး ဘာ မှ လည်း ပြန် မ ပြော ဘူး
ထိုင်း မှာ နေ ရ တာ အရမ်း ပင်ပန်း လာ ပြီ ဗျာ
ဘယ်ဥ က ပေါက် တဲ့ ကောင် လဲ မ သိ ဘူး
မင်း မ ကောင်း တော့ ပြည်သူပြည်သား တွေ ပါ ဒုက္ခရောက် ရ တဲ့ ဘဝ
ပူ တင်လဲ ဘာ ထူး လဲ တိုက်ခိုက် ခံ ရ ပြီး ဘတ် ကျပ် ပျက် နေ ပြီ

In [47]:
!echo "After cleaning..."
!head -n 10 task2_text_clean.txt

!echo ""
!echo "Word Segmented..."
!head -n 10 task2_text_word.txt

After cleaning...
ကိုယ့်နိုင်ငံကြီး အေးချမ်းသွားရင် ကိုယ့်နိုင်ငံ ပြန်တာပေါ့ သူတို့နိုင်ငံမှာ အရမ်း အနှိမ်ခံ ရတယ်ဗျာ
တကယ် လေ နိုင်ငံခြား သား တွေ အကုန် လုံး ကို တစ် ယောက် မ ကျန် အကုန် ပြန်လွှတ် စေ ချင် တာ ဂျပန် မှ လွဲ အကုန်လုံး ကို အဲ့လို သာ လုပ် လိုက် သူတို့ နိုင်ငံ သေချာပေါက် စီးပွားရေး ကျ ဆင်း ကုန်မှာ အေးရော။
ဂျပန် ထဲ မြန်မာ တွေ ဝင် လာ ပြီ ဆိုတော့ သူတို့ လန့် သွား တယ် ထင်တယ်
ဒီ အကြောင်း တွေ ကို ဂျပန် လို ပြော ပြီး တင် သင့် တယ် အခု လည်း ခွဲခြား ခြင်း ခံ ရ ပါတယ် သူတို့ က နေရာ က လိုချင် အပါး က ခို
တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာလို့ အများ ကြီး ဂျပန် ကို ဝင်လာ ကြ တာ လဲ
တူတူ ပဲ မ ရေ အလုပ် ထဲ က သူနာပြု မ လူ ကို မ တူ သ လို မ တန် သ လို အချိုး အမျိုးမျိုး နဲ့ စကား ပြောတယ် ညီမ ဆေး တိုက် ချိန် သူ့ ကို ပြ ရင် လုံးဝ မ ကြည့် ဘူး ဘာမှ လည်း ပြန် မ ပြော ဘူး
ထိုင်း မှာ နေ ရ တာ အရမ်း ပင်ပန်း လာ ပြီ ဗျာ
ဘယ် ဥ က ပေါက် တဲ့ ကောင် လဲ မ သိ ဘူး
မင်း မ ကောင်း တော့ ပြည်သူ ပြည်သား တွေ ပါ ဒုက္ခ ရောက် ရ တဲ့ ဘဝ
ပူတင် လဲ ဘာ ထူး လဲ တိုက် ခိုက် ခံ ရ ပြီး ဘတ်ကျပ် ပျက် နေ ပြီ

Word Segmented...
ကိုယ့် နိုင်ငံ ကြီး အေးချမ်း သွား ရင် ကိုယ့် နိုင်ငံ ပြန် တာ ပေါ့ သူ တို့ နိုင်ငံ မှာ အရမ်း အ နှိမ် ခံ ရ တယ် ဗျာ
တကယ် လေ နိုင်ငံခြားသား တွေ အကုန်လုံး ကို တစ် ယောက်မ ကျန် အကုန် ပြန်လွှတ် စေ ချင် တာ ဂျပန် မှ လွဲ အကုန်လုံး ကို အဲ့လို သာ လုပ် လိုက် သူ တို့ နိုင်ငံ သေချာပေါက် စီးပွားရေး ကျဆင်း ကုန် မှာ အေး ရော ။
ဂျပန် ထဲ မြန်မာ တွေ ဝင်လာ ပြီ ဆို တော့ သူ တို့ လန့် သွား တယ် ထင်တယ်
ဒီ အကြောင်း တွေ ကို ဂျပန် လို ပြော ပြီး တင် သင့် တယ် အခု လည်း ခွဲခြား ခြင်း ခံ ရ ပါတယ် သူ တို့ က နေရာ က လို ချင် အပါး က ခို
တရုတ် တွေ က ဂျပန် ကို မုန်း တယ် ပြော ပြီး ဘာ လို့ အများကြီး ဂျပန် ကို ဝင်လာ ကြ တာ လဲ
တူတူ ပဲ မ ရေ အလုပ် ထဲက သူနာပြု မ လူ ကို မ တူ သလို မ တန် သလို အချိုး အမျိုးမျိုး နဲ့ စကားပြော တယ် ညီမ ဆေးတိုက် ချိန် သူ့ ကို ပြ ရင် လုံးဝ မ ကြည့် ဘူး ဘာ မှ လည်း ပြန် မ ပြော ဘူး
ထိုင်း မှာ နေ ရ တာ အရမ်း ပင်ပန်း လာ ပြီ ဗျာ
ဘယ်ဥ က ပေါက် တဲ့ ကောင် လဲ မ သိ ဘူး
မင်း မ ကောင်း တော့ ပြည်သူပြည်သား တွေ ပါ ဒုက္ခရောက် ရ တဲ့ ဘဝ
ပူ တင်လဲ ဘာ ထူး လဲ တိုက်ခိုက် ခံ ရ ပြီး ဘတ် ကျပ် ပျက် နေ ပြီ

In [52]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    f1_score,
    classification_report,
    accuracy_score,
)

TEXT_FILE = "task2_text_word.txt"
LABEL_FILE = "task2_labels.csv"

LABEL_COLS = [
    "political",
    "racial/ethnic",
    "religious",
    "gender/sexual",
    "other",
]

# Load data
texts = pd.read_csv(
    TEXT_FILE, header=None, dtype=str, keep_default_na=False
)[0].tolist()

Y = pd.read_csv(
    LABEL_FILE, header=None
).to_numpy(dtype=int)

# Validate alignment
if len(texts) != len(Y):
    raise ValueError(
        f"Text/label mismatch: {len(texts)} texts vs {len(Y)} labels"
    )

if Y.shape[1] != len(LABEL_COLS):
    raise ValueError(f"Expected {len(LABEL_COLS)} label columns, got {Y.shape[1]}")

# Keep rows aligned; do not independently drop blank text lines
X = np.array(texts, dtype=object)

# Use the same random seed and test size as your baseline
indices = np.arange(len(X))
train_idx, test_idx = train_test_split(
    indices,
    test_size=0.2,
    random_state=42,
)

X_train, X_test = X[train_idx].tolist(), X[test_idx].tolist()
y_train, y_test = Y[train_idx], Y[test_idx]

# OPPA has already segmented the text.
# Split on whitespace to use the supplied word boundaries.
pipeline = TfidfVectorizer(
    analyzer="word",
    tokenizer=str.split,
    preprocessor=None,
    token_pattern=None,
    lowercase=False,
    ngram_range=(1, 2),
    sublinear_tf=True,
)

X_train_vec = pipeline.fit_transform(X_train)
X_test_vec = pipeline.transform(X_test)

model = OneVsRestClassifier(
    LinearSVC(C=1.0)
)
model.fit(X_train_vec, y_train)

predictions = model.predict(X_test_vec)

print("Accuracy (subset accuracy):",
      round(accuracy_score(y_test, predictions), 4))
print("Macro F1 (labels):",
      round(f1_score(y_test, predictions, average="macro",
                     zero_division=0), 4))
print("Micro F1:",
      round(f1_score(y_test, predictions, average="micro",
                     zero_division=0), 4))

print("\nPer-label report:")
print(classification_report(
    y_test,
    predictions,
    target_names=LABEL_COLS,
    zero_division=0,
))

print("\nPer-label F1:")
for label, score in zip(
    LABEL_COLS,
    f1_score(y_test, predictions, average=None, zero_division=0),
):
    print(f"{label}: {score:.4f}")

Accuracy (subset accuracy): 0.5551
Macro F1 (labels): 0.5098
Micro F1: 0.5693

Per-label report:
               precision    recall  f1-score   support

    political       0.77      0.64      0.70       641
racial/ethnic       0.62      0.29      0.40       172
    religious       0.91      0.54      0.68       188
gender/sexual       0.69      0.24      0.36       156
        other       0.65      0.31      0.42       440

    micro avg       0.74      0.46      0.57      1597
    macro avg       0.73      0.40      0.51      1597
 weighted avg       0.73      0.46      0.55      1597
  samples avg       0.34      0.33      0.33      1597


Per-label F1:
political: 0.7006
racial/ethnic: 0.3953
religious: 0.6756
gender/sexual: 0.3602
other: 0.4173

## Model Performance Comparison

| Model                         |   Macro F1 | Micro F1 | Accuracy |
| ----------------------------- | ---------: | -------: | -------: |
| BiLSTM                        |     0.1200 |        — |        — |
| Word TF-IDF + SVM             |     0.4130 |        — |        — |
| Raw Character TF-IDF + SVM    | **0.6252** |        — |        — |
| OPPA Word TF-IDF + Linear SVM |     0.5098 |   0.5693 |   0.5551 |

**Note:** Dashes indicate metrics not yet available. Accuracy for the OPPA model refers to subset accuracy, which requires all labels for a sample to match exactly.

### OPPA Word TF-IDF + Linear SVM: Per-Label Performance

| Label             | Precision |   Recall | F1-score |   Support |
| ----------------- | --------: | -------: | -------: | --------: |
| Political         |      0.77 |     0.64 |     0.70 |       641 |
| Racial/ethnic     |      0.62 |     0.29 |     0.40 |       172 |
| Religious         |      0.91 |     0.54 |     0.68 |       188 |
| Gender/sexual     |      0.69 |     0.24 |     0.36 |       156 |
| Other             |      0.65 |     0.31 |     0.42 |       440 |
| **Macro average** |  **0.73** | **0.40** | **0.51** | **1,597** |
| **Micro average** |  **0.74** | **0.46** | **0.57** | **1,597** |
| Weighted average  |      0.73 |     0.46 |     0.55 |     1,597 |

*Note: The comparison assumes consistent evaluation splits and settings across models. Verify this before drawing definitive conclusions.*

----